name: Build Artifacts

on:
  push:
    branches: [ "main" ]
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - runtimeIdentifier: win-x64
            os: windows-latest
          - runtimeIdentifier: win-x86
            os: windows-latest
          - runtimeIdentifier: linux-x64
            os: ubuntu-latest
          - runtimeIdentifier: linux-arm
            os: ubuntu-latest
          - runtimeIdentifier: linux-arm64
            os: ubuntu-latest
          - runtimeIdentifier: osx-x64
            os: macos-13
          - runtimeIdentifier: osx-arm64
            os: macos-14

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Determine Version
      id: set_version
      uses: PaulHatch/semantic-version@v5.4.0
      with:
        tag_prefix: "v"
        major_pattern: "(MAJOR)"
        minor_pattern: "(feat)"
        version_format: "${major}.${minor}.${patch}.${increment}"

    - name: Install Linux ARM Cross-compilation Dependencies
      if: matrix.os == 'ubuntu-latest' && (matrix.runtimeIdentifier == 'linux-arm' || matrix.runtimeIdentifier == 'linux-arm64')
      run: |
        sudo apt-get update
        sudo apt-get install -y clang zlib1g-dev
        if [ "${{ matrix.runtimeIdentifier }}" == "linux-arm64" ]; then
          sudo apt-get install -y gcc-aarch64-linux-gnu zlib1g-dev-arm64-cross
        elif [ "${{ matrix.runtimeIdentifier }}" == "linux-arm" ]; then
          sudo apt-get install -y gcc-arm-linux-gnueabihf zlib1g-dev-armhf-cross
        fi

    - name: Publish
      run: dotnet publish MehguViewer.Core.csproj -c Release -r ${{ matrix.runtimeIdentifier }} -o ./publish/${{ matrix.runtimeIdentifier }} /p:Version=${{ steps.set_version.outputs.version }}

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MehguViewer.Core_${{ matrix.runtimeIdentifier }}_${{ steps.set_version.outputs.version }}
        path: ./publish/${{ matrix.runtimeIdentifier }}

    - name: Upload to Release
      if: github.event_name == 'release'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd ./publish/${{ matrix.runtimeIdentifier }}
        # Zip the artifact for release upload
        zip -r MehguViewer.Core_${{ matrix.runtimeIdentifier }}_${{ steps.set_version.outputs.version }}.zip .
        gh release upload ${{ github.event.release.tag_name }} MehguViewer.Core_${{ matrix.runtimeIdentifier }}_${{ steps.set_version.outputs.version }}.zip
